availability_zone1: 
availability_zone2: 
availability_zone3: 

network_id1: 
network_id2: 
network_id3: 
network_id4: 
network_id5: 
network_id6:

security_group1: 
security_group2: 
security_group3: 
security_group4: 
security_group5: 
security_group6: 
