meta:
  environment: ~
  host: ~
  redirect_uri: ~
  properties: ~

jobs:
- name: docker
  instances: 1
  networks:
  - name: service-fabrik
    static_ips: (( merge || static_ips(1) ))
  resource_pool: default
  persistent_disk: 1024
  templates:
  - name: docker
    release: service-fabrik

- name: broker
  instances: 1
  networks:
  - name: service-fabrik
    static_ips: (( merge || static_ips(0) ))
  resource_pool: default
  templates:
  - name: service-fabrik-broker
    release: service-fabrik
  - name: service-fabrik-scheduler
    release: service-fabrik
  - name: service-fabrik-report
    release: service-fabrik
  - name: swarm_manager
    release: service-fabrik
  - name: route_registrar
    release: cf

releases:
- { name: cf, version: latest }
- { name: service-fabrik, version: latest }

networks: (( merge ))

properties: (( meta.properties ))
